language: android

sudo: false

jdk:
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x gradlew